tests
testNthUglyNumber
	self assert: (LeetCodeSolution solve264UglyNumberII: 1) equals: 1.
	self assert: (LeetCodeSolution solve264UglyNumberII: 2) equals: 2.
	self assert: (LeetCodeSolution solve264UglyNumberII: 3) equals: 3.
	self assert: (LeetCodeSolution solve264UglyNumberII: 4) equals: 4.
	self assert: (LeetCodeSolution solve264UglyNumberII: 5) equals: 5.
	self assert: (LeetCodeSolution solve264UglyNumberII: 10) equals: 12